name: Java CI

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'
        cache: 'gradle'
    # - uses: allure-framework/setup-allurectl@v1
    #   with:
    #     allure-endpoint: https://demo.testops.cloud
    #     allure-token: ${{ secrets.ALLURE_TOKEN }}
    #     allure-project-id: 1064
    - name: Run Tests
      run: |
        gradlew clean test

