name: Java CI

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'
        cache: 'gradle'
    # - uses: allure-framework/setup-allurectl@v1
    #   with:
    #     allure-endpoint: https://demo.testops.cloud
    #     allure-token: ${{ secrets.ALLURE_TOKEN }}
    #     allure-project-id: 1064
    - name: Run Tests
      run: |
        ./gradlew clean test
    - name: Install Allure CLI
      run: |
        wget https://github.com/allure-framework/allure2/releases/download/2.18.1/allure-2.18.1.zip
        unzip allure-2.18.1.zip -d /opt/
        sudo ln -s /opt/allure-2.18.1/bin/allure /usr/bin/allure
    - name: List directories
      run: |          
        allure generate --clean target/allure-results -o allure-report  
    - name: Upload Allure Report as Artifact
      uses: actions/upload-artifact@v3
      with:
        name: allure-report
        path: allure-report         

